### ISSUE TITLE
加入进度条

### ISSUE THREAD

**Issue by lr-tsinghua11** [A1phaN/tsinghua-ereserves-lib-downloader#1]
可否考虑在“正在获取第 {i} 章...”处增加预计时间，方便用户耐心等待（刚试了一下还挺慢的）

**Comment by A1phaN** [comment]
其实一开始考虑了这个问题，我本意是想展示一个总体的进度条，但是这样就需要先获取每一章的页数，不想太频繁请求API所以没写，想尽快发一个版本所以没有写的很细（×）下一个版本会做一点UI上的优化，包括那个下载按钮其实比其他的高 2px，我还没有找到原因

**Comment by A1phaN** [comment]
已添加章内页数的显示 9fe20ce
