### ISSUE TITLE
怎么不能用呢

### ISSUE THREAD

**Issue by foreverpiano** [A1phaN/tsinghua-ereserves-lib-downloader#3]
![图片](https://github.com/user-attachments/assets/5638bf03-a9a8-4f1d-8159-5a4dbfe3dfdd)
![图片](https://github.com/user-attachments/assets/61f31f75-a4d5-418a-86da-706defead798)
firefox130.0 64位 win11

**Comment by A1phaN** [comment]
我使用 Chrome 测试似乎是正常的，是否可以确认下脚本有没有真的执行（比如复制[整个脚本](https://github.com/A1phaN/tsinghua-ereserves-lib-downloader/blob/main/ereserves-lib.js)到控制台执行一下试试）？

**Comment by foreverpiano** [comment]
我是firefox，版本号是130.0，不能正常使用

**Comment by A1phaN** [comment]
已确认脚本没有被执行
